POST http://localhost:8080/api/company
Content-Type: application/json

{
  "name": "Test22 GmbH",
  "description": "tes1t test test",
  "contactName": "Hr. Franz Josef Leitner",
  "contactEmail": "leitner3@gmx.at",
  "contactPhoneNumber": "066042233445435",
  "url": "google.at",
  "locations": [
    {
      "streetName": "Bindermichl 35",
      "city": "Linz",
      "zipCode": "4020",
      "country": "Austria"
    },
    {
      "streetName": "Bindermichl 40",
      "city": "Linz",
      "zipCode": "4020",
      "country": "Austria"
    }
  ]
}
###
GET http://localhost:8080/api/company
###
GET http://localhost:8080/api/company/1
###
PUT http://localhost:8080/api/company/1
Content-Type: application/json

{
  "name": "Test23 GmbH",
  "description": "test1 test2 test3",
  "contactName": "Hr. Franzi",
  "contactEmail": "leitner4@gmx.at",
  "contactPhoneNumber": "066042212333445435",
  "url": "google2.at",
  "locations": []
}
###
DELETE http://localhost:8080/api/company/1
