POST localhost:8080/api/jobPosting/9
Content-Type: application/json


  {
    "fieldOfWork": "IT",
    "jobDescription": "Du suchst eine neue Herausforderung in der Entwicklung von Frontends im Dynatrace-Umfeld? Dann bist du bei uns genau richtig.",
    "jobTitle": "Frontend Entwickler",
    "postingDate": "2021-01-19",
    "timespan": "1 Monat"
  }

###

POST localhost:8080/api/jobPosting/10
Content-Type: application/json


{
  "fieldOfWork": "IT",
  "jobDescription": "Du suchst eine neue Herausforderung in der Entwicklung von Backend Services im Dynatrace-Umfeld? Dann bist du bei uns genau richtig.",
  "jobTitle": "Software Engineer",
  "postingDate": "2021-01-19",
  "timespan": "1 Monat"
}

###

POST localhost:8080/api/jobPosting/10
Content-Type: application/json


{
  "fieldOfWork": "IT",
  "jobDescription": "Du suchst eine neue Herausforderung. Willst all unseren Code testen?",
  "jobTitle": "Software Tester",
  "postingDate": "2021-01-19",
  "timespan": "1 Monat"
}

###

POST localhost:8080/api/jobPosting/8
Content-Type: application/json


{
  "fieldOfWork": "Design",
  "jobDescription": "Du bist ein Nerd, wenn es um Graphik Desing angeht. Dann bewirb dich jetzt.",
  "jobTitle": "Designer",
  "postingDate": "2021-01-19",
  "timespan": "1 Monat"
}
###
POST localhost:8080/api/jobPosting/8
Content-Type: application/json


{
  "fieldOfWork": "Finances",
  "jobDescription": "Du suchst eine neue Herausforderung in der Entwicklung von SAP Extensions im Banken-Umfeld? Dann bist du bei uns genau richtig.",
  "jobTitle": "SAP Guru",
  "postingDate": "2021-01-19",
  "timespan": "2 Monat"
}
###
GET localhost:8080/api/jobPosting
###
GET localhost:8080/api/jobPosting/3
###
GET localhost:8080/api/jobPosting/company/2
###
GET localhost:8080/api/jobPosting/fieldOfWork?fieldOfWork=Design
###
PUT localhost:8080/api/jobPosting/4
Content-Type: application/json

{
  "jobDescription": "This is a job. You should apply",
  "jobTitle": "A Job",
  "postingDate": "2020-11-29",
  "timespan": "1 months",
  "fieldOfWork": "IT"
}
###
PUT localhost:8080/api/jobPosting/4
Content-Type: application/json

{
  "timespan": "2 months"
}
###
DELETE localhost:8080/api/jobPosting/4
