POST localhost:8080/api/jobPosting/2
Content-Type: application/json

{
  "jobDescription": "This is a intersting a nice job. You should apply",
  "jobTitle": "Interesting Job",
  "postingDate": "2020-12-02",
  "timespan": "2 months",
  "fieldOfWork": "Design"
}
###
GET localhost:8080/api/jobPosting/3
###
GET localhost:8080/api/jobPosting/company/2
###
GET localhost:8080/api/jobPosting/fieldOfWork?fieldOfWork=Design
###
PUT localhost:8080/api/jobPosting/4
Content-Type: application/json

{
  "jobDescription": "This is a job. You should apply",
  "jobTitle": "A Job",
  "postingDate": "2020-11-29",
  "timespan": "1 months",
  "fieldOfWork": "IT"
}
###
PUT localhost:8080/api/jobPosting/4
Content-Type: application/json

{
  "timespan": "2 months"
}
###
DELETE localhost:8080/api/jobPosting/4
