### Get all Locations

GET http://localhost:8080/api/location

### Post Location

POST http://localhost:8080/location
Content-Type: application/json

{
  "name": "Test GmbH",
  "description": "test test test",
  "contactName": "Hr. Franz Josef Leitner",
  "contactEmail": "leitner@gmx.at",
  "contactPhoneNumber": "06602233445",
  "url": "google.at",
  "address": {
    "id": "ac130004-7523-18f7-8175-23ba3f0c0000"
  }
}
