POST http://localhost:8080/api/student
//Authorization: Bearer {{auth_token}}
Content-Type: application/json

  {
    "birthDate": "2001-12-02",
    "email": "elias2@gmail.com",
    "firstName": "Alexander",
    "lastName": "Kirchmair",
    "phoneNumber": "06601234567",
    "school": "HTBLA Leonding",
    "userName": "kirchi123",
    "description": "Hallo. Mein Name ist Alex Kirchi und ich bin 20 Jahre alt. Ich bin schon seit ich klein bin ein sogenannter Tech Freak. Ich will deshalb mehr und mehr im Bereich IT lernen. Der erste Schritt auf dieser Reise war das Absolvieren der HTBLA Leonding. Nun will ich den Weg weitergehen und praktische Erfahrung bei ihrem Unternehmen sammeln."
  }

###
GET http://localhost:8080/api/student/3
###
GET http://localhost:8080/api/student/4
###
GET http://localhost:8080/api/student/username/eliasroebl10
###
GET http://localhost:8080/api/student/email/elias1@gmail.com
###
PUT localhost:8080/api/student/4
Content-Type: application/json

{
  "birthDate": "2001-11-10",
  "email": "eliasroeb123l3@gmail.com",
  "firstName": "Elias",
  "lastName": "Röbl",
  "phoneNumber": "123123456789",
  "school": "HTBLA Leonding",
  "userName": "elia123s"
}
###
PUT localhost:8080/api/student/4
Content-Type: application/json

{
  "userName": "elias1251"
}
###
DELETE localhost:8080/api/student/4

